### ISSUE TITLE
jooq中如何使用java.util.Date

### ISSUE THREAD

**Issue by xngithub** [k55k32/learn-jooq#1]
目前javaTimeTypes为true使用的是Java8的日期时间API，如何将日期时间定义为Date类型呢

**Comment by diamondfsd** [comment]
可以参考一下 https://www.jooq.org/doc/3.13/manual/code-generation/custom-data-types/

**Comment by xngithub** [comment]
多谢多谢，可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "k55k32/learn-jooq"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 上午9:49
收件人:&nbsp;"k55k32/learn-jooq"<learn-jooq@noreply.github.com&gt;;
抄送:&nbsp;"faiting~"<861988851@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [k55k32/learn-jooq] jooq中如何使用java.util.Date (#1)





 
可以参考一下 https://www.jooq.org/doc/3.13/manual/code-generation/custom-data-types/
